#!/usr/bin/env bash
#
#/ command: third-party-packages:configure: "Configure the Jenkins instance"
#
#/ usage: rerun third-party-packages:configure [options]
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: 

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: third-party-packages:configure. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/configure/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/configure/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# ------------------------------
# Your implementation goes here.
# ------------------------------

# Install the plug-ins required by the example builds.
rerun jenkins:install-plugin --plugin-name git
rerun jenkins:install-plugin --plugin-name github-api
rerun jenkins:install-plugin --plugin-name github

# Make sure the Jenkins user can access GitHub over ssh:
sudo -u jenkins rerun ssh:add-host-key --type rsa --hostname github.com

# Restart Jenkins to enable the configuration.
rerun jenkins:restart

exit $?

# Done
